version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@healzjhb0k6m53n7_high?TNS_ADMIN=/app/wallet/
      - spring.datasource.username=ADMIN
      - spring.datasource.password=Tardigrado12
    restart: always
